### ISSUE TITLE
Notification Clicked Event didn't increase

### ISSUE THREAD

**Issue by bayuramadeza** [CleverTap/clevertap-flutter#12]
Hi Clevertap team

I want to know how to set event Notification Clicked manually in flutter? In Android i set up everything manually because event listener clevertap conflict with firebasemessaging. So i show notif manualyl with Flutter Local Notification . So, when user clicked the notification, Notification Clicked Event didn't record in user activity..i've tried to recordevent Notification Clicked manually but it didn't record as well. So how to record Notificaion Clicked Manually?

**Comment by darshanclevertap** [comment]
@bayuramadeza Have you done the below step as per documentation? 
 
```java
public class MyApplication extends FlutterApplication {
        @java.lang.Override
        public void onCreate() {
            ActivityLifecycleCallback.register(this); //<--- Add this before super.onCreate()
            super.onCreate();
        }
    }
```

**Comment by bayuramadeza** [comment]
yes i have done everything. But i didin't use clevertap listener in manifest. So i handle it in FCM services. But when notification appears and clicked by user. It didn't increase Notification Click event through I set CleverTap.recordEvent("Notification Clicked", )

**Comment by darshanclevertap** [comment]
@bayuramadeza Oh ok, yes we have not exposed the `pushNotificationClickedEvent` method in dart. You also can't use this - `CleverTap.recordEvent("Notification Clicked")` because `"Notification Clicked"` is a reserved event in our SDK. 

For now, you can raise a custom event like - `CleverTap.recordEvent("Push Notification Clicked")` and perform your analysis.

I'll mark this as an enhancement and we will pick this up soon and do a release to help you fix this in a couple of weeks.
