### ISSUE TITLE
Firebase DynamicLink UTM Parameters are not captured

### ISSUE THREAD

**Issue by kavinrajec** [CleverTap/clevertap-flutter#151]
When a user clicks on the Firebase DynamicLink to install the App, the UTM Visited properties are captured as follows, pls let me know what I m doing wrong.

Android:-
Referrer: wzrk://track?install=true&utm_source=(not%20set)&utm_medium=(not%20set)
utm_source: (not_set)
utm_medium: (not_set)

iOS:-
Referrer: com.healthsignz.aarthiscans://google/link/?match_type=unique&request_ip_version=IP%5FV6&utm_source=clevertap&utm_campaign=user%5Fengagement%5F17%5F02%5F2023&utm_medium=whatsapp&deep_link_id=https%3A%2F%2Faarthiscan%2Ecom%2F%3Fdeeplink%3Dprofile%2Fwallet&match_message=Link%20is%20uniquely%20matched%20for%20this%20device%2E
utm_source: clevertap
utm_medium: whatsapp
utm_campaign: user%5Fengagement%5F17%5F02%5F2023

**Comment by shivamsharma2710** [comment]
Hi @kavinrajec,

Thanks for reporting the issue. As I understand you're expecting to receive the `utm_source` and `utm_medium` fields on the Android platform.
   
To start the investigation, we need following details:

- CleverTap Flutter SDK version
- CleverTap Android SDK version
- DynamicLink URL which you've used for Android

**Comment by kavinrajec** [comment]
Hi @shivamsharma2710 
Yes that's what our expectation is and also in iOS if the UTM params values has any special characters(_,-) then it shows with encoded values. You can refer to my issue above. 
Ex:- utm_campaign: user%5Fengagement%5F17%5F02%5F2023 actual value to be - (user_engagement_17_02_2023).

Firebase Dynamic Link:
**Short Link** - https://aarthiscan.page.link/app
**Long Link** -https://aarthiscan.page.link/?link=https://aarthiscan.com/?deeplink%3Dprofile/wallet&apn=com.betamonks.aarthiscans&isi=1480823166&ibi=com.healthsignz.aarthiscans&ius=aarthi&st=Extra+5%25+Off+on+all+Online+Bookings&sd=India+%E2%80%98s+largest+integrated+scans+and+blood+testing+centre.&si=https://aarthiscan.com/wp-content/uploads/2022/10/Master-Health-Checkup.png&utm_campaign=userengagement_17_02_2023&utm_medium=whatsapp&utm_source=clevertap

Android SDK Version - 
iOS SDK Version - 4.1.5
Android SDK Version - 4.7.0

**Comment by shivamsharma2710** [comment]
@kavinrajec 

If the referrer parameter is not present or empty in the link, the Install Referrer client receives the following values as default: 
`utm_source=(not%20set)&utm_medium=(not%20set)`

So, in order to capture the UTM fields, you need to enclose them in the `referrer` parameter as below:

https://aarthiscan.page.link/?link=https://aarthiscan.com/?deeplink%3Dprofile/wallet&apn=com.betamonks.aarthiscans&isi=1480823166&ibi=com.healthsignz.aarthiscans&ius=aarthi&st=Extra+5%25+Off+on+all+Online+Bookings&sd=India+%E2%80%98s+largest+integrated+scans+and+blood+testing+centre.&si=https://aarthiscan.com/wp-content/uploads/2022/10/Master-Health-Checkup.png&utm_campaign=userengagement_17_02_2023&referrer=utm_source%3Dclevertap%26utm_medium%3Dwhatsapp

**Comment by shivamsharma2710** [comment]
Closing this issue. If you have further query related to the same, feel free to reopen the issue.
