### ISSUE TITLE
Clevertap plugin cause the app crasih

### ISSUE THREAD

**Issue by bayuramadeza** [CleverTap/clevertap-flutter#23]
Hi, In the last 5 days, I got few crash reports from my crashlytics.
And I found the issue in clevertap plugin  So I want you to know about this crash issue.
The device that crash is Google Pixex 3 XL with Android 11

<img width="611" alt="Screen Shot 2020-11-20 at 13 51 58" src="https://user-images.githubusercontent.com/32892647/99768690-cf892780-2b37-11eb-9693-0f1899630ae2.png">

Please fix this issue.

**Comment by darshanclevertap** [comment]
@bayuramadeza This was fixed in the latest release [v1.2.0](https://github.com/CleverTap/clevertap-flutter/releases/tag/1.2.0)
There are a few breaking changes on the Android side so please refer to [this document](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) before proceeding.

**Comment by darshanclevertap** [comment]
@bayuramadeza Kindly confirm if you're still facing or not.

**Comment by hdeyana** [comment]
Hi this breaking change cause over 5k+ crash in our google play report.

Some suggestion
1. Add Breaking change warning in readme.md
3. Add Breaking change warning in changelog.md
2. Make it version 2.0.0, so it will not auto updated by pub if its from 1.1 to 1.2

**Comment by darshanclevertap** [comment]
@hdeyana Apologize for the inconvenience, we'll ensure breaking changes are conveyed more effectively on Github as well.
I hope that fixing all the breaking changes has helped in resolving the crashes.
