### ISSUE TITLE
setCleverTapPushClickedPayloadReceivedHandler not called when app is cold started from a push notification

### ISSUE THREAD

**Issue by Irfan-KV** [CleverTap/clevertap-flutter#70]
The requirement is to receive key-value pair from the push notification, and navigate to the required page. It works fine when the app is in background or foreground. But when the app is killed and we open the notification, the handler is not called.

**Comment by darshanclevertap** [comment]
This is a limitation of Flutter. When the app is cold started, we cannot set the callback for `setCleverTapPushClickedPayloadReceivedHandler` on the Flutter/Dart side of the app. The native side callback is already set but when it tries to provide the data to Flutter/Dart, since the app is cold-starting we cannot pass it.

**Comment by Irfan-KV** [comment]
Can't we find any workaround for this? This works with other packages. So I
believe this can be fixed.

**Comment by mufayed** [comment]
any solution or work around for that issue ?
